const NOTIFY_ACTUAL_PROJECTS = "NOTIFY_ACTUAL_PROJECTS";
const ADD_PROJECT_LIST = "ADD_PROJECT_LIST";
const UPDATE_STORAGE_PROJECTS = "UPDATE_STORAGE_PROJECTS";

export { NOTIFY_ACTUAL_PROJECTS, ADD_PROJECT_LIST, UPDATE_STORAGE_PROJECTS };
